### ISSUE TITLE
Item in the inventory to leave the arena.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#100]
Hi,

It would be great to have an item like a door in the 9th slot to leave the arena. 
What do you think about that ?

Thanks ! :D

**Comment by Shynixn** [comment]
Hey, 

I don't think this should be a usecase of BlockBall as there are many plugins where you can bind commands to items. Simply bind the /bbleave command to a door item, however as BlockBall currently only allows custom armors instead of full inventories, getting the door into the player's inventory after joining a game could be a difficult task.

**Comment by TheIntelloBox** [comment]
So you don't want to add it ?

**Comment by Shynixn** [comment]
No, I don't want to add a door item. Supporting full inventories would be a different case but please submit another issue for this.

**Comment by TheIntelloBox** [comment]
Okay. ;)
