### ISSUE TITLE
Converter for the new version ?

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/BlockBall#57]
Hey,

Is there a converter for the new version ?

**Comment by Shynixn** [comment]
No, unfortunately there is no converter as the actions behind certain options changed drastically and your game would behave in a strange way when the values only partially get converted.

**Comment by TheIntelloBox** [comment]
So I must recreate the arena with the new commands ? ?

**Comment by Shynixn** [comment]
I would like to call it Chat-UI... it is really necessary, I can give you some examples:

- The Ball alone has got now more than 40 config options instead of around 5 
- The spectator settings where removed completely (they are coming back later)
- DoubleJump has got a cooldown system now which has to be configured correctly
- ...
