### ISSUE TITLE
Missing dependencies after setting up workspace

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/BlockBall#65]
I've cloned this repo and set up my local workspace for this project.
I definitely followed the instructions on [document](https://shynixn.github.io/BlockBall/build/html/api/index.html#setup-your-personal-blockball-workspace), however I can't build the project due to missing dependencies.  
And what kind of spigot lib do I need? Please explain exactly.  

Missing dependencies for root pom.xml:
- org.apache.maven.plugins:maven-gpg-plugin:1.5

Missing ones for blockball-api:
- com.github.shynixn.ball:ball-api:1.0-SNAPSHOT

for blockball-bukkit-api:
- com.github.shynixn.blockball:blockball-api:5.0.1
- com.github.shynixn.ball:ball-bukkit-api:1.0-SNAPSHOT
- net:minecraft18R1:1.0 **(... up to)** net:minecraft112R1:1.0

for blockball-bukkit-plugin:
- com.github.shynixn.blockball:blockball-bukkit-api:5.0.1
- com.github.shynixn.ball:ball-bukkit-core:1.0-SNAPSHOT
- com.google.inject:guice:4.1.0
- org.bstats:bstats-bukkit:RELEASE
- me.clip:placeholderapi:RELEASE
- net.milkbowl.vault:VaultAPI:RELEASE
- com.sk89q:worldguard:RELEASE
- com.zaxxer:HikariCP:RELEASE
- org.jetbrains.kotlin:kotlin-test:1.2.21
- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.21
- org.slf4j:slf4j-jdk14:1.7.25
- org.xerial:sqlite-jdbc:RELEASE
- ch.vorburger.mariaDB4j:mariaDB4j:RELEASE
- org.mockito:mockito-core:RELEASE
- org.junit.jupiter:junit-jupiter-api:5.0.0-M4

**Comment by LazoYoung** [comment]
I'm using IntelliJ IDEA FYI

**Comment by Shynixn** [comment]
ok, I just give you a final warning as BlockBall is writting in Kotlin instead of java ^^ 

I'll put here a tutorial and add it later to the documentation:

- All dependencies except "net:minecraft18R1:1.0 (... up to) net:minecraft112R1:1.0" should be automatically resolved, downloaded and used by maven. 

**Maven dependencies:**
- Check your Settings/Build, Executiopn, Deployment/Build Tools/Maven settings in IntelliJ IDEA and uncheck "Work offline" if checked. 
- Then go the toolbar on the right where it should display "Maven Projects" (You need to enable View/Toolbar Buttons) and open it. 
Press on the reimport all maven projects button.

**Spigot libaries*
- Use spigot Build Tools to build the following version. Here is a [picture of the PetBlocks](https://shynixn.github.io/PetBlocks/build/html/_images/help1.jpg) workspace.

 java -jar BuildTools.jar --rev 1.8
- java -jar BuildTools.jar --rev 1.8.3
- java -jar BuildTools.jar --rev 1.8.8
- java -jar BuildTools.jar --rev 1.9
- java -jar BuildTools.jar --rev 1.9.4
- java -jar BuildTools.jar --rev 1.10
- java -jar BuildTools.jar --rev 1.11
- java -jar BuildTools.jar --rev 1.12

- Put them into the lib folder.
- After you have done all of this,  press on compile in the BlockBall root project.

**Comment by Shynixn** [comment]
EDIT: Also, if you want to make changes to the ball physics engine, you can find it as standalone project [here](https://github.com/Shynixn/Ball). The engine is written in Java.

**Comment by LazoYoung** [comment]
Thanks, I will give it a try this weekend

**Comment by LazoYoung** [comment]
Sorry, I can't make time to test it until I graduate my highschool next year.  
I confirm that you have answered my question, you may close this issue :)

**Comment by Shynixn** [comment]
Hahaha ok. Thanks for the message otherwise these sections get closed after ~3 months.
